version: "3.7"
services:
  db:
    image: postgres:10.1-alpine
  app:
    build:
      context: .
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      [
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./start.sh",
      ]
